server:
  port: 8082

spring:
  datasource:
    username: wujia_dev
    password: Wujia!@#
    url: jdbc:mysql://rm-2ze9f44ol605d099mro.mysql.rds.aliyuncs.com:3306/wujia_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  #  data:
#    mongodb:
#      uri: mongodb://39.97.186.122:27017/wj
  redis:
    database: 0
    timeout: 1000
    # Redis服务器地址
    host: 39.97.186.122
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
  pool:
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 10
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接池中的最大空闲连接
    max-idle: 20
    # 连接池中的最小空闲连接
    min-idle: 10

#在application.yml引入log4j2.yml
logging:
  config: classpath:log4j2.yml

wj:
  oss:
    point: http://oss-cn-beijing.aliyuncs.com
    key: LTAIBcmvGzaNrYGd
    secret: 0PWTcwRaXzlb7XWG9IflqCc9Y6xmfA
    bucket: wujia01
    access: https://wujia01.oss-cn-beijing.aliyuncs.com/
  path:
    card: images/card/icon
    service: images/service/icon
  send:
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    action: SendSms
    version: 2017-05-25
    SignName: 吾家智工
    TemplateCode: SMS_166655952


